document.addEventListener("DOMContentLoaded",()=>{const $=id=>document.getElementById(id);const user=JSON.parse(localStorage.getItem("geriUser")||'{"nome":"Maria Silva","email":"maria@email.com"}');const ag=JSON.parse(localStorage.getItem("geriAgendamento")||"null");
if($("userName"))$("userName").textContent=user.nome||"Maria Silva";if($("confPaciente"))$("confPaciente").textContent=user.nome||"Maria Silva";
if($("loginForm"))$("loginForm").addEventListener("submit",e=>{e.preventDefault();let email=$("email").value.trim(),senha=$("senha").value;if(email==="maria@email.com"&&senha==="123456"){localStorage.setItem("geriUser",JSON.stringify({nome:"Maria Silva",email}));location.href="datas-horarios.html"}else if(senha.length>=6){localStorage.setItem("geriUser",JSON.stringify({nome:"Paciente",email}));location.href="datas-horarios.html"}else $("loginMsg").textContent="E-mail ou senha inválidos. Use a senha de demonstração 123456."});
if($("cadastroForm"))$("cadastroForm").addEventListener("submit",e=>{e.preventDefault();if($("cadSenha").value!==$("cadSenha2").value){$("cadMsg").className="error";$("cadMsg").textContent="As senhas não conferem.";return}localStorage.setItem("geriUser",JSON.stringify({nome:$("cadNome").value,email:$("cadEmail").value}));$("cadMsg").textContent="Cadastro realizado com sucesso!";setTimeout(()=>location.href="datas-horarios.html",700)});
document.querySelectorAll(".time.available").forEach(b=>b.onclick=()=>{localStorage.setItem("geriData","15/09/2026");localStorage.setItem("geriHorario",b.dataset.time);location.href="confirmacao.html"});
document.querySelectorAll(".date-option").forEach(b=>b.onclick=()=>{localStorage.setItem("geriData",b.dataset.date);localStorage.setItem("geriHorario","07:30");location.href="confirmacao.html"});
if($("dataConfirmada")){$("dataConfirmada").textContent=localStorage.getItem("geriData")||"15/09/2026";$("horarioConfirmado").textContent=localStorage.getItem("geriHorario")||"07:30"}
if($("confirmar"))$("confirmar").onclick=()=>{let d=localStorage.getItem("geriData"),h=localStorage.getItem("geriHorario");if(!d||!h){alert("Selecione uma data e um horário antes de confirmar.");return}let a={nome:user.nome||"Maria Silva",data:d,horario:h,protocolo:"GERI-"+Math.floor(100000+Math.random()*900000)};localStorage.setItem("geriAgendamento",JSON.stringify(a));location.href="sucesso.html"};
if($("protocolo")&&ag){$("protocolo").textContent=ag.protocolo;$("sPaciente").textContent=ag.nome;$("sData").textContent=ag.data;$("sHorario").textContent=ag.horario}
if($("agendaLista"))$("agendaLista").innerHTML=ag?`<h2>Consulta geriátrica</h2><div class="agenda-item"><b>${ag.data} às ${ag.horario}</b><br>Paciente: ${ag.nome}<br>Protocolo: ${ag.protocolo}</div><div class="notice"><b>Status:</b> Agendamento confirmado.</div>`:'<div class="empty">Você ainda não possui agendamentos.</div>';
if($("dataForm"))$("dataForm").onsubmit=e=>{e.preventDefault();$("dataMsg").className="success";$("dataMsg").textContent="Data adicionada com sucesso (demonstração)."};if($("horaForm"))$("horaForm").onsubmit=e=>{e.preventDefault();$("horaMsg").className="success";$("horaMsg").textContent="Horário adicionado com sucesso (demonstração)."};});